-- dap-config.lua: SUPERSEDED
--
-- C# (coreclr/netcoredbg) → lua/gpltaylor/plugins/csharp.lua
-- Go (delve)              → lua/gpltaylor/plugins/golang.lua + nvim-dap-go
--
-- This file is no longer loaded anywhere.
-- Kept to preserve git history; safe to delete.
